name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0" # every sunday at midnight

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Docker build and test
        run: |
             # Workaround to provide additional free space for testing.
             #   https://github.com/actions/virtual-environments/issues/2840
             sudo rm -rf /usr/share/dotnet
             sudo rm -rf /opt/ghc
             sudo rm -rf "/usr/local/share/boost"
             sudo rm -rf "$AGENT_TOOLSDIRECTORY"
             .bin/build-image.sh
             .bin/test-image.sh

  deploy:
    needs: [build]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "arm64,arm"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: publish release docker image
        uses: docker/build-push-action@v3
        with:
          repository: toolisticon/kalilinux
          tags: latest
        if: contains( github.ref, 'master' ) || contains( github.base_ref, 'master' )

      - name: publish preview docker image
        uses: docker/build-push-action@v3
        with:
          repository: toolisticon/kalilinux
          tags: next
        if: contains( github.ref, 'develop' ) || contains( github.base_ref, 'develop' )
